### PR TITLE
chore: upgrade to docker 1.43

### PR DESCRIPTION
**Pull request by leon3s**
Hey, i wanted to help by upgrading docker to the latest version.

### CODE REVIEW

**Comment by fussybeaver** [comment]
In principal this looks like a good PR... We should check if there's some ongoing upstream changes in the moby project around the container changes API endpoint.

**Comment by leon3s** [comment]
The tests wasn't passing and i'm not sure why. That's why i closed, i can reopen if you want nothing changed much.
But the serialization for the container changes endpoint wasn't passing anymore

**Comment by fussybeaver** [comment]
Yeh this needs some more work... I tried generating the models again, but it looks like enums are broken in the current templates with 1.43.

**Comment by leon3s** [comment]
@fussybeaver 
Sorry i didn't unlocked time to work on the java part to make this work.
Thank you for your time and work on this!

**Comment by fussybeaver** [comment]
No worries, thanks for the pushing this forwards on the agenda.

**Pull request merged**
