### PR TITLE
fix: missing tty options in StartExecOptions

### PR DESCRIPTION
**Pull request by leon3s**
Source: https://docs.docker.com/engine/api/v1.43/#tag/Exec/operation/ExecStart

### CODE REVIEW

**Comment by fussybeaver** [comment]
Thanks, I think we never added this parameter, because in my testing it didn't seem to affect the API output in any way - you'd need to wrap this endpoint in a pseudo tty library and a command-line interface to actually make it act like a tty. 

Now I'm checking the underlying moby code, it looks like the `tty` parameter sets a different response content type? https://github.com/moby/moby/blob/fa2f6f98beb4d9d6fd814e63c28cefac7f90ccbc/api/server/router/container/exec.go#L122 

Are you finding this parameter useful?

**Comment by leon3s** [comment]
Hey yes, instead of returning a Stream where docker write writing for each stdout and stderr the number 0 or 1 to specify what kind of output is it send a single stream with all output. It also add colors and detach keys as the behavior differt when the command write in a tty.
You can test the behavior of this using docker cli.

```sh
docker run -dt --name test-exec alpine:latest
# No colors
docker exec test-exec ls -l --color=auto /
# With colors
docker exec -t test-exec ls -l --color=auto /
```

**Comment by fussybeaver** [comment]
I guess the same could be asked about other options like https://github.com/fussybeaver/bollard/blob/6ecdb1402cf5ef0a6d65e0b3282898df37b86566/codegen/swagger/src/models.rs#L886 and there are probably others..

It's probably a good idea to use the generated type in these cases :+1:

**Comment by fussybeaver** [comment]
I'll merge this for now, can think about using the generated types

**Pull request merged**
