### PR TITLE
Remove `Connect` type parameter in `Docker`

### PR DESCRIPTION
**Pull request by veeg**
As mentioned in [#17](https://github.com/fussybeaver/bollard/issues/17#issuecomment-468173704), the issues with requiring a `Connect` type parameter to the Docker structure entails that it is not usable in certain scenarios.

This PR introduces the following changes:
* Remove the `Connect` type parameter.
* Remove the generic `Docker::connect_with` method.
* Introduce a `Docker::connect_with_host_to_reply` that is only available in test.
* Convert all unit tests from `Docker::connect_with` to `Docker::connect_with_host_to_reply`.
* Introduce `Docker::connect_with_local` and `Docker::connect_with_local_defaults`.

This change is a *breaking* change, and will require a major version bump if merged (e.g., 0.3).

### CODE REVIEW

**Comment by veeg** [comment]
I see the issue with how the examples in `lib.rs` are constructed, they rely on the `Docker::connect_with` method to construct and run the doc examples, and these are ran as integration test, which means that cfg(test) is not enabled, so with this approach we cannot use `HostToReplyConnector`.

One option would be to wrap all those in a `Docker::connect_local()` and add no_run attribute to those lib doc tests. Opinions?

**Comment by fussybeaver** [comment]
Hi @veeg , thanks for this. 

Yes, I'm OK with your suggestions on the lib doctests - I think `no_run` is fine, although I guess if you're using `no_run` maybe it's more useful to use one of the more common connection paradigms, like `docker::connect_with_unix_defaults()`, because these doctests will be shown as examples in the github README.

**Comment by veeg** [comment]
I updated the PR to include two new connection methods:
* `Docker::connect_with_local_defaults`
* `Docker::connect_with_local`

This allowed me to update the doc tests in `src/lib.rs` to use this local connection,
such that it would be available on both platforms (doc tests are ran on both windows and linux)

**Comment by fussybeaver** [comment]
OK, looking good... couple of things to wrap things up, and then we can merge and make a release:

- I think we'll need a minor version number bump to 0.3.0 in `Cargo.toml` and also in `lib.rs` 
https://github.com/fussybeaver/bollard/pull/19/files#diff-b4aea3e418ccdb71239b96952d9cddb6L22

- The README needs updating - I used the cargo readme plugin https://github.com/livioribeiro/cargo-readme and run it with:
```
cargo readme --no-title --no-badges > README.md
```
When it's merged I can package and publish the crate, and do the git release.

**Comment by veeg** [comment]
I updated the PR to include the version bump and updated README, as requested.
This PR now includes both changes to the library, as well as project version updates.
(I like to separate these, as its not necessarily up to the PR to determine when a bump should occur)

**Comment by fussybeaver** [comment]
Nice work!

**Pull request merged**
