### PR TITLE
Updates to the v1.40 upstream Docker API

### PR DESCRIPTION
**Pull request by fussybeaver**
- Updates the API stubs according to upstream changes. 
- Removes the `deny_unknown_fields` constraint (thanks @edigaryev )
- Adds mount option to creating containers

### CODE REVIEW

**Comment by edigaryev** [comment]
Just wondering: do you plan to support only the latest version of Docker API in this library?

Because specifying an API version that is higher than of the server API version when making request effectively causes Docker daemon to return an error: https://github.com/moby/moby/blob/4e83c90ae8362a8205e3728e8fcb655a713a0d87/api/server/middleware/version.go#L58-L60

You can check this yourself by running:

```
$ DOCKER_API_VERSION=1.41 docker version | grep Error
Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40
```

Also see https://github.com/eldesh/dockworker/pull/51.

**Comment by fussybeaver** [comment]
Thanks for pointing that out - it does seem appropriate to have an environment variable, like the official docker client to toggle the API version. Is that something you would like to tackle in a separate PR ?

**Comment by edigaryev** [comment]
>it does seem appropriate to have an environment variable

I'm not sure if that'd be the right way to do tackle this, see the comment pointing to https://github.com/moby/moby/issues/25498 here: https://github.com/gesellix/docker-client/issues/25.

**Comment by fussybeaver** [comment]
It does seem like one would need to do something like:

https://github.com/moby/moby/blob/3a4b51ebb8b6559ce4c8f126a7533066369c6182/client/client.go#L223-L246

Although, I'm wondering whether it would just be easier to call the API without a version (like dockworker does).

**Comment by fussybeaver** [comment]
Added version negotiation in https://github.com/fussybeaver/bollard/pull/27 . @edigaryev is that something you'd be happy with ?

**Comment by edigaryev** [comment]
Yes, that works for me, thanks!

**Pull request merged**
