### PR TITLE
Fix errors under features

### PR DESCRIPTION
**Pull request by fanatid**
Currently `NoCertPathError` will be imported only if `ssl` feature activated, if activate only `tls` it will not be possible compile project with this crate.

### CODE REVIEW

**Comment by fussybeaver** [comment]
Hmm... looks OK, but I wonder why the integration test case was working for this? Is it just a doc-test compile error ?

https://github.com/fussybeaver/bollard/blob/master/.circleci/config.yml#L16-L29

At any rate, I would release this as version 6.1 if we merge it, because we are deprecating openssl and the native TLS code path in preference for rustls in #76 .

**Comment by fanatid** [comment]
Test did not had correct features set. Was success because compiled binary had 0 tests.

**Comment by fussybeaver** [comment]
Thanks...

**Comment by fanatid** [comment]
Thanks for quick merge! Can you release patch?

**Comment by fussybeaver** [comment]
Yes, I'll do a release.

**Pull request merged**
