### PR TITLE
Some ipamConfig elements are not present sometimes

### PR DESCRIPTION
**Pull request by ipoupaille**
Seen on alpine linux 3.11 armv7 on rbpi2.
Docker version 19.03.5, build 633a0ea838f10e000b7c6d6eed1623e6e988b5bb

### CODE REVIEW

**Comment by fussybeaver** [comment]
Thanks, looks good, although the doctests need fixing.. you can run them with `cargo test --doc`

**Comment by ipoupaille** [comment]
> 
> 
> Thanks, looks good, although the doctests need fixing.. you can run them with `cargo test --doc`

Sorry, I forgot this part. This is done now

**Comment by fussybeaver** [comment]
Nice, needs rebase/merge.

**Comment by ipoupaille** [comment]
> Nice, needs rebase/merge.

Done

**Pull request merged**
