### PR TITLE
Services support

### LINKED ISSUE #50: docker service support
Is there currently anything planned regarding the docker service api?

If not, would a PR for that be welcome?
I'd be willing to implement it in the next few weeks.

Awesome project btw.

### PR DESCRIPTION
**Pull request by fussybeaver**
I've disabled the windows tests for services, because `docker swarm init` seems to hang in appveyor.

Supersedes #51 

Fixes #50

### CODE REVIEW

**Comment by fussybeaver** [comment]
@iyzana feel free to open a new PR if you want to continue working on more services API endpoints. I'll get this in master for the moment. Let me know if I've missed anything..

**Comment by iyzana** [comment]
@fussybeaver There are a few problems @bittrance found that i didn't pull into my PR yet.
Here's their fork of my fork:
https://github.com/bittrance/bollard/commits/services-support

**Comment by fussybeaver** [comment]
Thanks, I've merged that work in. Hopefully that's fine for an initial implementation..

**Comment by bittrance** [comment]
Sorry, I've been a bit absent. Thanks for including my fixes. With those, [swarm-ecr-deployer](https://github.com/bittrance/swarm-ecr-deployer) has successfully been performing list and.update operations in our staging Docker 19.09 Swarm (API version 1.40). I'll switch over to this branch and verify that it continues to operate properly.

**Comment by fussybeaver** [comment]
Nice project @bittrance - thanks for the patches both! I'll merge this now and make a release.

**Pull request merged**
