### PR TITLE
Use named pipe for buildkit ssh agent auth on Windows

### PR DESCRIPTION
**Pull request by paul-hansen**
Fixes: #442 by implementing the ssh agent forwarding using named sockets on Windows.

### Draft Status
Compiles, but needs testing yet to see if it actually works.  My understanding of ssh agent and how it's used here is still very basic, so may discover it needs significant work depending on the results of testing.

### CODE REVIEW

**Comment by fussybeaver** [comment]
Great, Thank you! Doesn't look too complicated. We need to get a test case, I think we can copy the [one in circle ci](https://github.com/fussybeaver/bollard/blob/6d4c130660d46460c8f40fbc71d9eb6a10958608/.circleci/config.yml#L104-L117) into appveyor.. 

There are some parts that we probably don't need in this PR:
 - No need for formatting changes in `codegen/swagger/src/models.rs` as it's a generated file. 
 - Also not sure about the clippy warnings commit - e.g. we still run many of those tests / examples on windows successfully, maybe we should tackle that separately..

**Comment by paul-hansen** [comment]
> Also not sure about the clippy warnings commit - e.g. we still run many of those tests / examples on windows successfully, maybe we should tackle that separately..

Yeah now that you mention it I think I might have messed up fixing the dead code warnings on some of the test functions, wasn't really looking to see if some of those were just feature gated. Removed that commit. Might open up a followup PR.

> We need to get a test case, I think we can copy the [one in circle ci](https://github.com/fussybeaver/bollard/blob/6d4c130660d46460c8f40fbc71d9eb6a10958608/.circleci/config.yml#L104-L117) into appveyor.. (let me know if that's a bit beyond you, happy to take a look)

I'll give it a shot, I haven't worked with circleci or appveyor before but I'm familiar with github actions and it seems similar. Worst case, hopefully I can figure out how to run what that test you linked (super helpful thank you!) does locally and let you know any dependencies I needed etc.

**Comment by fussybeaver** [comment]
> > We need to get a test case, I think we can copy the [one in circle ci](https://github.com/fussybeaver/bollard/blob/6d4c130660d46460c8f40fbc71d9eb6a10958608/.circleci/config.yml#L104-L117) into appveyor.. (let me know if that's a bit beyond you, happy to take a look)
> 
> I'll give it a shot, I haven't worked with circleci or appveyor before but I'm familiar with github actions and it seems similar. Worst case, hopefully I can figure out how to run what that test you linked (super helpful thank you!) does locally and let you know any dependencies I needed etc.

Now I think about it, that test case won't work particularly well as you need an ssh-agent server that's exposing a named pipe ...

**Comment by paul-hansen** [comment]
Yeah on windows you can start the ssh-agent service by running powershell as admin and running this:
```ps1
Set-Service ssh-agent -StartupType Manual
Start-Service ssh-agent
```
Not sure how to use that in our tests yet. I assumed we'd need to run a Windows container for it or something but maybe there's a way around that.

Took a break to work on some other things, welcome to add commits to this branch if you want (allow edits by maintainers is on). I might have some more time to dig on it tomorrow.

**Comment by fussybeaver** [comment]
I took a stab at it [in a branch](https://github.com/paul-hansen/bollard/compare/windows-buildkit...fussybeaver:bollard:ND/windows-buildkit?expand=1), but couldn't get a windows git server working correctly in a docker container.

In the meantime, I think we can just [disable this codepath for windows](https://github.com/fussybeaver/bollard/pull/444), so we can get a patch release out... I don't think I'll be able to look at this further without sorting out a VM with docker running on it.

**Comment by paul-hansen** [comment]
Yeah that sound good to me, I haven't had luck figuring out how to test it correctly either. Combining not really much about ssh forwarding and not knowing appveyor was a bit much for me with the time I have. Appreciate you getting a patch out there!

Closing for now as I don't expect I'll have time to work on this till after our site launches (hopefully in the next couple months). Feel free to adopt it or use anything from it though. Thanks again!

**Pull request closed without merging**
